name: Athena
description: Universally Designed Mobile Application to Enable Secondary School Students to Manage their Daily School Life

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.3
  camera: ^0.2.4
  image_picker: ^0.4.10
  dio: ^1.0.6
  transparent_image: ^0.1.0
  photo_view: ^0.0.10
  flutter_advanced_networkimage: 0.3.9
  cached_network_image: 0.5.0+1
  flutter_sound: ^1.1.5
  flutter_swiper: ^1.1.4
  file_picker: ^1.1.1
  chewie: ^0.9.6
  video_player: ^0.10.0+2
  audioplayers: ^0.7.8
  zefyr: ^0.3.1
  flutter_colorpicker: ^0.2.1
  marquee: ^1.1.0
  datetime_picker_formfield: ^0.1.8
  charts_flutter: ^0.5.0
  flutter_launcher_icons: ^0.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "assets/icon/icon3.png"
  ios: "assets/icon/icon_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icon/icon3.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.otf
        - asset: assets/fonts/NotoSansTC-Bold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Arimo
      fonts:
      - asset: assets/fonts/Arimo-Regular.ttf
      - asset: assets/fonts/Arimo-Italic.ttf
        style: italic
      - asset: assets/fonts/Arimo-Bold.ttf
        weight: 700
    - family: B612
      fonts:
      - asset: assets/fonts/B612-Regular.ttf
      - asset: assets/fonts/B612-Italic.ttf
        style: italic
      - asset: assets/fonts/B612-Bold.ttf
        weight: 700
    - family: FiraSans
      fonts:
      - asset: assets/fonts/FiraSans-Regular.ttf
      - asset: assets/fonts/FiraSans-Italic.ttf
        style: italic
      - asset: assets/fonts/FiraSans-Bold.ttf
        weight: 700
    - family: JosefinSans
      fonts:
      - asset: assets/fonts/JosefinSans-Regular.ttf
      - asset: assets/fonts/JosefinSans-Italic.ttf
        style: italic
      - asset: assets/fonts/JosefinSans-Bold.ttf
        weight: 700
    - family: Oxygen
      fonts:
      - asset: assets/fonts/Oxygen-Regular.ttf
      - asset: assets/fonts/Oxygen-Bold.ttf
        weight: 700
    - family: Teko
      fonts:
      - asset: assets/fonts/Teko-Regular.ttf
      - asset: assets/fonts/Teko-Bold.ttf
        weight: 700
    - family: Cuprum
      fonts:
      - asset: assets/fonts/Cuprum-Regular.ttf
      - asset: assets/fonts/Cuprum-Bold.ttf
        weight: 700
    - family: Orbitron
      fonts:
      - asset: assets/fonts/Orbitron-Regular.ttf
      - asset: assets/fonts/Orbitron-Bold.ttf
        weight: 700
    - family: Rajdhani
      fonts:
      - asset: assets/fonts/Rajdhani-Regular.ttf
      - asset: assets/fonts/Rajdhani-Bold.ttf
        weight: 700
    - family: Monda
      fonts:
      - asset: assets/fonts/Monda-Regular.ttf
      - asset: assets/fonts/Monda-Bold.ttf
        weight: 700
    - family: Philosopher
      fonts:
      - asset: assets/fonts/Philosopher-Regular.ttf
      - asset: assets/fonts/Philosopher-Italic.ttf
        style: italic
      - asset: assets/fonts/Philosopher-Bold.ttf
        weight: 700
    - family: SignikaNegative
      fonts:
      - asset: assets/fonts/SignikaNegative-Regular.ttf
      - asset: assets/fonts/SignikaNegative-Bold.ttf
        weight: 700
    - family: Amaranth
      fonts:
      - asset: assets/fonts/Amaranth-Regular.ttf
      - asset: assets/fonts/Amaranth-Italic.ttf
        style: italic
      - asset: assets/fonts/Amaranth-Bold.ttf
        weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
